## Exercises: 4. Arrays

#### Problem 1

Write a julia function called `hasduplicates` that takes an array and returns true if there is any element that appears more than once. It should not modify the original array.

Hint: one can convert an array into a [set](https://docs.julialang.org/en/v1/base/collections/#Base.Set).

#### Solution

In [1]:
function hasduplicates(arr::AbstractArray)
    unique_arr = Set(arr)  # Convert array to a set to remove duplicates
    return length(arr) != length(unique_arr)
end

array1 = [1, 2, 3, 4, 5]
array2 = [1, 2, 3, 4, 4]

println(hasduplicates(array1))  # Output: false (no duplicates)
println(hasduplicates(array2))  # Output: true (duplicates exist)

false
true


#### Problem 2

a) Create an array with values ranging from 10 to 49

b) Return the reverse of a 1D array (first element becomes last)

c) Create a 3x3 matrix with values ranging from 0 to 8

d) Create a 2d array with 1 on the border and 0 inside

#### Solution

In [5]:
a = [10:49;]

40-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
  ⋮
 41
 42
 43
 44
 45
 46
 47
 48
 49

In [19]:
a = [1:5;]
a[end:-1:1] #faster
# reverse(a)

5-element Vector{Int64}:
 5
 4
 3
 2
 1

In [6]:
a = reshape(0:8,3,3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 0  3  6
 1  4  7
 2  5  8

In [8]:
a = zeros(5,5)
a[1,:] .= 1
a[end,:] .= 1
a[2:end-1,1] .= 1 
a[2:end-1,end] .= 1
a[:,1] .= 1;a[:,end] .= 1
a

5×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0

#### Problem 3

If there are 23 students in your class, what are the chances that two of you have the same birthday? You can estimate this probability by generating random samples of 23 birthdays and checking for matches.

Tip:
You can generate random birthdays with rand(1:365).

#### Solution

In [20]:
function simulate_birthday_experiment(num_simulations::Int)
    num_matches = 0

    for _ in 1:num_simulations
        # Generate birthdays for 23 students
        birthdays = [rand(1:365) for _ in 1:23]

        # Check for duplicates in the birthdays array
        if length(birthdays) != length(Set(birthdays))
            num_matches += 1
        end
    end

    return num_matches / num_simulations
end

num_simulations = 100000
probability_of_match = simulate_birthday_experiment(num_simulations)

println("Estimated probability of at least one pair of students having the same birthday:")
println("    ", probability_of_match)

Estimated probability of at least one pair of students having the same birthday:
    0.50698


#### Additional material

2x2 matrix vs array of arrays

In [12]:
A = [[1, 2], [3, 4]]

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [10]:
A[1][2]

2

In [6]:
B = [[1, 2] [3, 4]]

2×2 Matrix{Int64}:
 1  3
 2  4

In [7]:
B[1, 2]

3

In [11]:
B[1][2]

BoundsError: BoundsError: attempt to access Int64 at index [2]